task: hellaswag_decontam
dataset_path: jasonkrone/hellaswag_with_dev_hpo
dataset_name: null
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
test_split: validation
process_docs: !function utils.process_docs
doc_to_text: "Question: {{ query }}\nA. {{ endings[0] }}\nB. {{ endings[1] }}\nC. {{ endings[2] }}\nD. {{ endings[3] }}\nAnswer:"
doc_to_target: "{{gold}}"
target_delimiter: " "
doc_to_choice: ["A", "B", "C", "D"]
should_decontaminate: true
doc_to_decontamination_query: "Question: {{ query }}\nA. {{ endings[0] }}\nB. {{ endings[1] }}\nC. {{ endings[2] }}\nD. {{ endings[3] }}\nAnswer: {{gold}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
