##########################################
#                 Imports                #
##########################################

include: configs/train/wimsy/wimsy_7b/architectures/_llama_7b_architecture_yaml
include: configs/train/wimsy/wimsy_7b/shared_hyper_params/_full_run_shared_hyper_params_yaml
include: configs/train/wimsy/wimsy_7b/phase_hyper_params/_wimsy_7b_phase1_hyper_params_yaml
include: configs/train/wimsy/data/_pretrain_phase1_data_mixes_yaml
include: configs/train/wimsy/_wimsy_template_yaml

##########################################
#             Weights & Biases           #
##########################################

wandb:
  project_name: wimsy
  run_name: wimsy-7b-phase1b-12-08-24

############################################
#              Checkpointing               #
############################################

ckpt:
  checkpointer: fsdp_checkpointer
  strip_prefix: _orig_mod.
  remote_output_dir: s3://jpt-output
  local_output_dir: /output
  copy_dir: /copy
  ckpt_interval: *ckpt_interval


###########################################
#                  Data                   #
###########################################

data:
  data_loader:
    id: streaming_data_loader
    args:
      pin_memory: True
      batch_size: *batch_size
      num_workers: *num_workers

  train_dataset:
    id: streaming_text_dataset
    args:
      load_mask: False
      streams:
        *pretrain_phase_1b_train_mix
      batch_size: *batch_size
      batching_method: random
      shuffle: True
      shuffle_seed: *seed
      keep_zip: False

  dev_dataset:
    id: streaming_text_dataset
    args:
      load_mask: False
      streams:
        *pretrain_phase_1b_dev_mix
      batch_size: *batch_size
      batching_method: random
      shuffle: True
      shuffle_seed: *seed
      keep_zip: False


