task: piqa_hpo
dataset_path: jasonkrone/piqa_with_dev_hpo
dataset_name: null
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
test_split: null
target_delimiter: " "
doc_to_text: "Question: {{goal}}\nA. {{sol1}}\nB. {{sol2}}\nAnswer:"
doc_to_target: "{% if label == 0 %}{{sol1}}{% else %}{{sol2}}{% endif %}"
doc_to_choice: !function utils.doc_to_choice
should_decontaminate: true
doc_to_decontamination_query: goal
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: nll_per_char
    aggregation: mean
    higher_is_better: false
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
