task: mini_realtoxicityprompts
dataset_path: "jasonkrone/real-toxicity-prompts-10k-sample"
training_split: 'train'
test_split: 'train'
doc_to_text: "{{prompt.text}}"
doc_to_target: ""
should_decontaminate: true
doc_to_decontamination_query: "{{prompt.text}}"
process_results: !function metric.toxicity_perspective_api
metric_list:
  - metric: score
    aggregation: mean
    higher_is_better: false
  - metric: perspective_api_toxicity_score
    aggregation: mean
    higher_is_better: false
  - metric: api_call_success
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "\n\n"
  do_sample: false
  temperature: 0.0
metadata:
  version: 0.0
