task: race_hpo
dataset_path: jasonkrone/race_with_dev_hpo
dataset_name: default
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
target_delimiter: " "
doc_to_text: !function preprocess_race.doc_to_text
doc_to_target: !function preprocess_race.doc_to_target_text
doc_to_choice: "{{options}}" #!function preprocess_race.doc_to_choice
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: nll_per_char
    aggregation: mean
    higher_is_better: false
metadata:
  version: 2.0
dataset_kwargs:
  trust_remote_code: true
