task: race_decontam
dataset_path: jasonkrone/race_with_dev_hpo
dataset_name: default
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
test_split: test
target_delimiter: " "
doc_to_text: !function preprocess_race.doc_to_text
doc_to_target: !function preprocess_race.doc_to_target
doc_to_choice: !function preprocess_race.doc_to_choice
should_decontaminate: true
doc_to_decontamination_query: !function preprocess_race.doc_to_decontamination_query
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 2.0
dataset_kwargs:
  trust_remote_code: true