task: arc_easy_hpo_4choice
dataset_path: jasonkrone/arc_easy_with_dev_hpo_4choice_only
dataset_name: null
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
target_delimiter: " "
doc_to_text: "Question: {{ question }}\n{% for i in range(choices.label|length) %}{{ choices.label[i] }}. {{ choices.text[i] }}\n{% endfor %}Answer:"
doc_to_target: !function utils.doc_to_target
doc_to_choice: "{{choices.text}}"
should_decontaminate: true
doc_to_decontamination_query: "Question: {{question}}\nAnswer:"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: nll_per_char
    aggregation: mean
    higher_is_better: false
metadata:
  version: 1.0
