task: triviaqa_wiki_hpo
dataset_path: jasonkrone/trivia_qa_with_dev_hpo
dataset_name: null
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
description: "Answer these questions:\n\n"
doc_to_text: "Q: {{question}}\nA:"
doc_to_target: !function utils.doc_to_target
doc_to_choice: !function utils.doc_to_choice
should_decontaminate: true
doc_to_decontamination_query: question
target_delimiter: " "
fewshot_delimiter: "\n"
fewshot_config:
  sampler: first_n
  samples:
    - question: Who was President when the first Peanuts cartoon was published?
      answer:
        aliases:
          - Harry Truman
    - question: Which American-born Sinclair won the Nobel Prize for Literature in 1930?
      answer:
        aliases:
          - Sinclair Lewis
    - question: Where in England was Dame Judi Dench born?
      answer:
        aliases:
          - York
    - question: William Christensen of Madison, New Jersey, has claimed to have the world's biggest collection of what?
      answer:
        aliases:
          - Beer Cans
    - question: In which decade did Billboard magazine first publish and American hit chart?
      answer:
        aliases:
          - 30s
    - question: null
      answer:
        aliases:
          - null
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: nll_per_char
    aggregation: mean
    higher_is_better: false
metadata:
  version: 3.0
