task: winogrande_decontam
dataset_path: jasonkrone/winogrande_with_dev_hpo
dataset_name: null
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
test_split: validation
target_delimiter: " "
doc_to_text: "Question: Which sentence is more likely?\nA. {{ choices[0] }}\nB. {{ choices[1] }}\nAnswer:"
doc_to_target: answer
doc_to_choice: ["A", "B"]
should_decontaminate: true
doc_to_decontamination_query: "Question: Which sentence is more likely?\nA. {{ choices[0] }}\nB. {{ choices[1] }}\nAnswer: {{answer}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true