include: truthfulqa_mc1.yaml
task: truthfulqa_mc2_decontam
doc_to_target: 0
doc_to_choice: "{{mc2_targets.choices}}"
process_results: !function utils.process_results_mc2
should_decontaminate: True
doc_to_decontamination_query: !function utils.doc_to_decontamination_query
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 2.0
