name: prep-books

resources:
  cloud: aws
  instance_type: i3.16xlarge
  disk_size: 600
  region: us-east-1
  image_id: ami-0ea5e9630dcf98849

file_mounts:
  /artifacts:
    source: s3://jpt-artifacts
    mode: COPY

workdir: ~/Developer/jpt

setup: |
  echo "setup"

run: |
  echo "run"
