name: prep-stack

resources:
  cloud: aws
  instance_type: i3.16xlarge
  disk_size: 800
  region: us-east-1
  image_id: ami-0ea5e9630dcf98849

file_mounts:
  /artifacts:
    source: s3://jpt-artifacts
    mode: COPY

num_nodes: 8

workdir: ~/Developer/jpt

setup: |
  echo "setup"

run: |
  cd ~/sky_workdir
  requirements_path="requirements/data_requirements.txt"
  env_name="prep_data"
  source ./bash/setup.sh; activate_or_create_conda_env $env_name $requirements_path
  
  sudo chmod go+rw /artifacts
  
  rm -rf ~/.cache/huggingface/dataprep/json/*
  rm -rf /home/ubuntu/data
  
  config_dir=./configs/preprocess/ctx_len_4096_tokenizer_tiktoken
  source keys.env; python -m preprocessing.prep_data --config $config_dir/prep_stack.yaml
  
