task: drop_hpo
dataset_path: jasonkrone/drop_remove_empty_train_answers
output_type: multiple_choice
training_split: null
validation_split: train
process_docs: !function utils.process_docs
doc_to_text: "Passage: {{passage}}\nQuestion: {{question}}\nAnswer: "
doc_to_target: !function utils.doc_to_target
doc_to_choice: !function utils.doc_to_choice
target_delimiter: " "
should_decontaminate: true
doc_to_decontamination_query: !function utils.doc_to_decontamination_query
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: nll_per_char
    aggregation: mean
    higher_is_better: false
metadata:
  version: 3.0
dataset_kwargs:
  trust_remote_code: true
