substitutions:
  dataset: open-web-math 
  source_extension: json.gz

vars:
  cleanup: &do_cleanup True
  is_distributed: &is_distributed False

  downloader:
    urls_path: &urls_path ./preprocessing/dataset_urls/dolma_v1dot7/open_web_math.txt
    num_shards: &num_shards 1
    source_location: &source_location url

  elastic_search_indexer:
    num_documents_to_index: &num_documents_to_index null

  decontaminator:
    drop_entire_doc: &drop_entire_doc True
    drop_doc_contamination_threshold: &drop_doc_contamination_threshold 1.0

  map_jsonl:
    keys_to_remove: &keys_to_remove
      - metadata # dataset loader can't handle dicts
      - created  # inconsistent datatype on created breaks dataloader
      - attributes
      - doc
  
  split_maker:
    # TODO: you gotta change this for each dataset
    # list here: https://docs.google.com/spreadsheets/d/1Gc2RKYD6QuzXwG0Vj54VQxRYxXcydTu9QxV8zEHrJAE/edit#gid=0
    avg_num_tokens_per_doc: &avg_num_tokens_per_doc 4344
    dev_size: &dev_size 5000

include: _prep_dolma_template_yaml 