wandb:
  project_name: baseline_eval
  run_name: null

compute:
  device: cuda
  is_distributed: True

seed: &seed 414

eval_vars:
  do_apply_chat_template: &do_apply_chat_template False
  ifeval_max_gen_toks: &ifeval_max_gen_toks 3840

include: configs/eval/test_eval/_test_evals_yaml

baselines:
  ########################################################################################
  #                                        Base Models                                   #
  ########################################################################################

  ########## Llama-2 ##########
  llama-2-7b:
    id: hf
    args: pretrained=meta-llama/Llama-2-7b-hf

# model info will be set by scripts to the baseline info above
model:
  id: null
  args: null

test_eval:
  clear_cache: True
  include_path: ./tasks
  log_samples: True
  limit: null
  output_path: /output/baselines
  tasks:
    <<: *test_eval_tasks
   