task: openbookqa_decontam
dataset_path: jasonkrone/openbookqa_with_dev_hpo
dataset_name: null
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
test_split: test
target_delimiter: " "
doc_to_text: "Question: {{ question_stem }}\n{% for i in range(choices.label|length) %}{{ choices.label[i] }}. {{ choices.text[i] }}\n{% endfor %}Answer:"
doc_to_target: "{{answerKey.lstrip()}}"
doc_to_choice: "{{choices.label}}"
should_decontaminate: true
doc_to_decontamination_query: "Question: {{ question_stem }}\n{% for i in range(choices.label|length) %}{{ choices.label[i] }}. {{ choices.text[i] }}\n{% endfor %}Answer: {{answerKey.lstrip()}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0