wandb:
  project_name: baseline_eval
  run_name: null

compute:
  device: cuda
  is_distributed: True

seed: &seed 414

baselines:
  # realtoxicity
  replicate_gemma2_9b:
    id: hf
    args: pretrained=google/gemma-2-9b

# model info will be set by scripts to the baseline info above
model:
  id: null
  args: null

test_eval:
  include_path: ./tasks
  log_samples: True
  limit: null
  output_path: /output/baselines_07_30_24
  tasks:
    realtoxicityprompts:
      shot: 0
      batch_size: auto