name: temp-phased-train

resources:
  accelerators: [A100:2] # [A100:8, A100-80GB:4, A100:4, A100-80GB:2, A100:2] #{A100}
  cloud: gcp
  region: us-central1
  disk_size: 1000

num_nodes: 2

file_mounts:
  /output:
    source: s3://jpt-output
    mode: MOUNT
  /books_data:
    source: s3://books-mds-decontaminated-ctx-4096-tokenizer-tiktoken
    mode: COPY 

workdir: ~/Developer/jpt

setup: |
  remote_sqsh_path="s3://jpt-apps/pt2dot6_11_30_24.sqsh"
  
  local_sqsh_path="/tmp/train.sqsh"
  env_name=train_env
  
  # install enroot
  # TODO: i think this hangs on GCP waiting for user input, so need to fix that
  source ./bash/setup.sh; install_enroot
  
  # copy the sqsh file
  echo "copying sqsh file"
  aws s3 cp $remote_sqsh_path $local_sqsh_path
  
  # create the enroot env 
  echo "creating enroot env"
  enroot create --name $env_name $local_sqsh_path
 


run: |

  # expected to exec with --env CONFIG=./configs/train/llm_exps/exp_0_baseline_tweaks/baseline.yaml
  
  # kill $(lsof -ti :1234 | head -n 1)
  
  num_nodes=`echo "$SKYPILOT_NODE_IPS" | wc -l`
  
  root_dir=/sky_workdir
  #config_path=${root_dir}/${CONFIG}
  #echo "config path: ${config_path}"
  
  source ./bash/setup.sh ; clean_tmp
  
  env_name=train_env

  config1=./configs/train/wimsy_7b/pretrain_wimsy_7b_phase1.yaml
  config2=./configs/train/wimsy_7b/pretrain_wimsy_7b_phase2.yaml
  
  enroot start \
    --rw \
    --mount ~/sky_workdir:/sky_workdir \
    --mount /books_data:/books_data \
    --mount /tmp:/tmp \
    --mount /output:/output \
    --env SKYPILOT_NUM_NODES=$num_nodes \
    --env SKYPILOT_NODE_IPS \
    --env SKYPILOT_NUM_GPUS_PER_NODE \
    --env SKYPILOT_NODE_RANK \
    --env TRANSFORMERS_CACHE=/tmp/.cache \
    $env_name \
    /sky_workdir/bash/run_training.sh run_train_in_phases $config1 $config2
