name: decontam-wiki

resources:
  cloud: aws
  instance_type: i3.16xlarge
  disk_size: 600
  region: us-east-1
  image_id: ami-0ea5e9630dcf98849

workdir: ~/Developer/jpt

setup: |
  # download the artifact
  source ~/sky_workdir/keys.env; aws s3 cp s3://jpt-artifacts/test_and_dev_13_grams.jsonl.gz /home/ubuntu/test_and_dev_13_grams.jsonl.gz

  # setup elastic serach
  sudo mkdir /es
  sudo chown -R 1000:0 /es
  sudo docker run -p 9200:9200 -p 9300:9300 -e "xpack.security.enabled=false" -e "discovery.type=single-node" -v /es:/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:8.15.2

run: |
  cd ~/sky_workdir

  # install conda
  requirements_path="requirements/data_requirements.txt"
  env_name="decontam3"
  source ./bash/setup.sh; activate_or_create_conda_env $env_name $requirements_path  

  config_path=./configs/decontaminate/wiki_decontaminate.yaml
  #source keys.env; python -m preprocessing.prep_data --config $config_path

  rm /home/ubuntu/data/download-wiki/documents/with_lines_and_paths_contaminated_spans.json
  rm /home/ubuntu/spans_with_no_location.jsonl

  source keys.env; python -m preprocessing.recover_ids_and_line_nums --config $config_path