task: gsm8k_mc_hpo
dataset_path: jasonkrone/gms8k_mc_with_dev_hpo
dataset_name: null
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
target_delimiter: " "
doc_to_text: "Question: {{Question}}\nA. {{A}}\nB. {{B}}\nC. {{C}}\nD. {{D}}\nAnswer:"
doc_to_target: !function utils.doc_to_target #"{{Answer}}"
doc_to_choice: !function utils.doc_to_choice #["A", "B", "C", "D"]
should_decontaminate: true
doc_to_decontamination_query: "{{Question}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: nll_per_char
    aggregation: mean
    higher_is_better: false
metadata:
  version: 1.0
