task: boolq_decontam
dataset_path: jasonkrone/boolq_with_dev_hpo
dataset_name: null
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
test_split: validation
doc_to_text: "Background: {{passage}}\n\nQuestion: {{question}}?\nA. no\nB. yes\nAnswer:"
doc_to_target: "{% if label == 1 %}B{% else %}A{% endif %}"
target_delimiter: " "
doc_to_choice: ["A", "B"]
should_decontaminate: true
doc_to_decontamination_query: "Background: {{passage}}\n\nQuestion: {{question}}?\nA. no\nB. yes\nAnswer: {% if label == 1 %}B{% else %}A{% endif %}"
metric_list:
  - metric: acc
metadata:
  version: 2.0
dataset_kwargs:
  trust_remote_code: true