task: boolq_hpo
dataset_path: jasonkrone/boolq_with_dev_hpo
dataset_name: null
output_type: multiple_choice
training_split: train
validation_split: dev_hpo
doc_to_text: "Background: {{passage}}\n\nQuestion: {{question}}?\nA. yes\nB. no\nAnswer:"
doc_to_target: "{% if label == 0 %}no{% else %}yes{% endif %}"
target_delimiter: " "
doc_to_choice: ["yes", "no"]
should_decontaminate: true
doc_to_decontamination_query: passage
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: nll_per_char
    aggregation: mean
    higher_is_better: false
metadata:
  version: 2.0
dataset_kwargs:
  trust_remote_code: true