task: commonsense_qa_hpo_4choice
dataset_path: jasonkrone/commonsense_qa_with_dev_hpo_4choice
training_split: train
validation_split: dev_hpo
output_type: multiple_choice
doc_to_text: "Question: {{ question.strip() }}\nA. {{choices['text'][0]}}\nB. {{choices['text'][1]}}\nC. {{choices['text'][2]}}\nD. {{choices['text'][3]}}\nAnswer:"
doc_to_target: !function utils.doc_to_target # answerKey
target_delimiter: " "
doc_to_choice: "{{choices['text']}}"  # ['A', 'B', 'C', 'D']
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: nll_per_char
    aggregation: mean
    higher_is_better: false
