task: commonsense_qa_decontam
dataset_path: jasonkrone/commonsense_qa_with_dev_hpo
training_split: train
validation_split: dev_hpo
test_split: validation
output_type: multiple_choice
doc_to_text: "Question: {{ question.strip() }}\nA. {{choices['text'][0]}}\nB. {{choices['text'][1]}}\nC. {{choices['text'][2]}}\nD. {{choices['text'][3]}}\nE. {{choices['text'][4]}}\nAnswer:"
doc_to_target: answerKey
target_delimiter: " "
doc_to_choice: ['A', 'B', 'C', 'D', 'E']
should_decontaminate: true
doc_to_decontamination_query: "Question: {{ question.strip() }}\nA. {{choices['text'][0]}}\nB. {{choices['text'][1]}}\nC. {{choices['text'][2]}}\nD. {{choices['text'][3]}}\nE. {{choices['text'][4]}}\nAnswer: {{answerKey}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
