name: capacity-res-head-node

resources:
  instance_type: m5.8xlarge
  cloud: aws
  region: us-east-1
  zone: us-east-1f

num_nodes: 1

workdir: ~/Developer/jpt

setup:
  echo "setup"

run: |
  echo "running"