# we use standard lambada here b/c eluther open-ai version doesn't have validation split
task: lambada_hpo
dataset_path: lambada
dataset_name: null
output_type: loglikelihood
validation_split: validation
doc_to_text: "{{text.split(' ')[:-1]|join(' ')}}"
doc_to_target: "{{' '+text.split(' ')[-1]}}"
should_decontaminate: true
doc_to_decontamination_query: "{{text}}"
metric_list:
  - metric: perplexity
    aggregation: perplexity
    higher_is_better: false
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: nll_per_char
    aggregation: mean
    higher_is_better: false
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true