task: drop_decontam
dataset_path: EleutherAI/drop
output_type: generate_until
training_split: train
validation_split: validation
process_docs: !function utils.process_docs
doc_to_text: "Passage: {{passage}}\nQuestion: {{question}}\nAnswer: "
doc_to_target: !function utils.doc_to_target
target_delimiter: ""
process_results: !function utils.process_results
should_decontaminate: true
doc_to_decontamination_query: !function utils.doc_to_decontamination_query
generation_kwargs:
  # coppied from llama3
  max_gen_toks: 32
  until:
    - "\n\n"
metric_list:
  - metric: em
    aggregation: mean
    higher_is_better: true
  - metric: f1
    aggregation: mean
    higher_is_better: true
metadata:
  version: 3.0
dataset_kwargs:
  trust_remote_code: true
